# Generated by Django 2.2.1 on 2019-06-28 15:53

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('store_img', models.ImageField(blank=True, upload_to='images/menu/')),
                ('description', models.CharField(max_length=200)),
                ('price_won', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('store_img', models.ImageField(blank=True, upload_to='images/store/')),
                ('min_price_won', models.PositiveIntegerField()),
                ('delivery_fee_won', models.PositiveIntegerField()),
                ('menu_intro', models.TextField()),
                ('menu_origin', models.CharField(max_length=300)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuOptionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('required_yn', models.BooleanField()),
                ('category_order', models.PositiveSmallIntegerField()),
                ('menu', smart_selects.db_fields.ChainedForeignKey(chained_field='store', chained_model_field='store', on_delete=django.db.models.deletion.CASCADE, to='store.Menu')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('extra_price_won', models.PositiveIntegerField()),
                ('category', smart_selects.db_fields.ChainedForeignKey(chained_field='store', chained_model_field='store', on_delete=django.db.models.deletion.CASCADE, to='store.MenuOptionCategory')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_order', models.PositiveSmallIntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='store', chained_model_field='store', on_delete=django.db.models.deletion.CASCADE, to='store.MenuCategory'),
        ),
        migrations.AddField(
            model_name='menu',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
    ]
