# Generated by Django 2.2.1 on 2019-06-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('titleBG', models.CharField(max_length=30)),
                ('titleColor', models.CharField(max_length=30)),
                ('path', models.TextField()),
                ('bodyBG', models.CharField(max_length=30)),
                ('bodyColor', models.CharField(max_length=30)),
                ('img_src', models.CharField(max_length=100)),
                ('ellipsis', models.CharField(max_length=100)),
                ('jibun', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('regDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
