# Generated by Django 2.2.1 on 2019-06-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='titleBG',
            field=models.CharField(max_length=100),
        ),
    ]
