# Generated by Django 2.2.1 on 2019-06-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_auto_20190624_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='bodyBG',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='area',
            name='bodyColor',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='area',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='area',
            name='path',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='titleBG',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='area',
            name='titleColor',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
