# Generated by Django 2.2.1 on 2019-06-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('walletAddress', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=50)),
                ('lastAccess', models.DateTimeField(auto_now_add=True)),
                ('regDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
